name: Application deployment
run-name: Application deployment run

on: 
  push:
    # branches:
    #   - main

jobs:
  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: docker-login
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build-image
        run: docker build -t marmitalandia/marmita-webserver -f ./build/Dockerfile .
      
      - name: push-to-hub
        run: docker push marmitalandia/marmita-webserver
          
  # pull-webserver: 
  #   runs-on: ubuntu-latest
  #   needs: [deploy-to-dockerhub]
  #   if: needs.deploy-to-dockerhub.result == 'success'
  #   steps:
  #     - name: push-docker-hub
  #       run:

  #     - name: ssm-pull-image
  #       run: 


        