name: Repository linter
run-name: repository linting run

on:
  pull_request:
    branches:
      - main    

env:
  TFLINT_VERSION: v0.52.0

jobs: 
    Run-TFlint:
        runs-on: ubuntu-latest
        steps:
          - name: Check out current repo
            uses: actions/checkout@v4

          - name: Setup terraform
            uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: "~1.9.0"

          - uses: terraform-linters/setup-tflint@v4
            name: Setup TFLint
            with:
              tflint_version: ${{ env.TFLINT_VERSION }}
    
          - name: Run tflint init
            run: tflint --init

          - name: Change directory to infra
            run: cd infra/
      
          - name: Run tflint on infra directory
            run: |
              tflint --recursive --config ${{ github.workspace }}/.tflint.hcl
